import { createClient } from '@supabase/supabase-js';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import 'dotenv/config';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Supabase Client using environment keys
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Error: Missing SUPABASE_URL or SUPABASE_ANON_KEY in .env file.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function uploadStructuredData() {
  const jsonDir = path.join(__dirname, '../data/structured_json');

  try {
    const files = await fs.readdir(jsonDir);
    const jsonFiles = files.filter(file => file.endsWith('.json'));

    console.log(`🚀 Found ${jsonFiles.length} structured files. Initiating Supabase upload database sync...\n`);

    for (const file of jsonFiles) {
      console.log(`📦 Processing ${file}...`);
      const filePath = path.join(jsonDir, file);
      const fileRawData = await fs.readFile(filePath, 'utf-8');
      
      // Parse the JSON structure generated by Gemini
      const parsedData = JSON.parse(fileRawData);
      const records = parsedData.airline_rules;

      if (!records || !Array.isArray(records) || records.length === 0) {
        console.log(`   ⚠️ No valid records found inside ${file}, skipping.`);
        continue;
      }

      // Upsert records into the database table (on conflict, do nothing to prevent duplicates)
      const { data, error } = await supabase
        .from('airline_baggage_rules')
        .upsert(records, { onConflict: 'record_hash' });

      if (error) {
        console.error(`   ❌ Failed to sync records for ${file}:`, error.message);
      } else {
        console.log(`   ✅ Successfully synced ${records.length} matrix constraints to the cloud!`);
      }
    }

    console.log('\n🏁 Database pipeline ingestion sequence completed successfully!');

  } catch (error) {
    console.error('❌ Root error during database uploading workflow:', error.message || error);
  }
}

uploadStructuredData();